name:Node js CI
on:
push:     
branches: -main   
pull_request:      
branches:   -main
jobs:    
build: 
run-on: unbuntu-latest
strategy:      
matrix:    node-version:[20.x]
steps: 
-name: checout repository    
uses: action/checkout@v3       
-name:Set up Node.js    
uses: action/setup-node@v3    
with: node-version: ${{ matrix.node-version }}   
-name: install dependencies  
run: npm install  
- name start application
run:npm start
